; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "OpenVINO AI Plugins for Audacity"
#define MyAppPublisher "Intel Corporation"
#define MyAppURL "https://github.com/intel/openvino-plugins-ai-audacity/"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{944D0498-C914-46E9-97E0-813B726CB0B0}
AppName={#MyAppName}
AppVersion={#AI_PLUGIN_VERSION}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
;DefaultDirName=C:\Program Files\Audacity
;DefaultDirName={reg:HKCR\Audacity.Project,Path|C:\Program Files\Audacity}
DefaultDirName={code:FindAudacity}
UsePreviousAppDir=no
AppendDefaultDirName=no
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
DirExistsWarning=no
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=mysetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64os
; "ArchitecturesInstallIn64BitMode=x64" requests that the install be
; done in "64-bit mode" on x64, meaning it should use the native
; 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64os
InfoBeforeFile=LICENSE_text.txt
DisableWelcomePage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; OpenVINO & GenAI libraries
Source: "{#OPENVINO_GENAI_DIR}\runtime\bin\intel64\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
Source: "{#OPENVINO_GENAI_DIR}\runtime\3rdparty\tbb\bin\*.dll"; DestDir: "{app}"; Flags: ignoreversion 

; Libtorch
Source: "{#LIBTORCH_DIR}\lib\*.dll"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

; Audacity module
Source: "{#BUILD_FOLDER}\audacity-build\{#AUDACITY_BUILD_CONFIG}\modules\mod-openvino.dll"; DestDir: "{app}\modules"; Flags: ignoreversion

[Icons]
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Code]
function FindAudacity(Param: String): String;
var
  V: String;
begin
  if RegQueryStringValue(HKCR, 'Audacity.Project\shell\open\command', '', V) then
    begin
      V := RemoveQuotes(V);
      Result := ExtractFilePath(V);
    end
  else
    begin
       MsgBox('Location of Audacity installation could not be determined. Note that it was looking for a 64-bit installation of Audacity. Please manually set Audacity installation folder that contains Audacity.exe', mbInformation, MB_OK);
       Result := 'C:\Program Files\Audacity'
    end;
end;

function NextButtonClick(PageId: Integer): Boolean;
begin
    Result := True;
    
    if (PageId = wpSelectDir) and not FileExists(ExpandConstant('{app}\Audacity.exe')) then begin
        MsgBox('Audacity does not seem to be installed in that folder.  Please select a folder that contains Audacity.exe', mbError, MB_OK);
        Result := False;
        exit;
    end;
end;



